      <div data-custom-class="body">
      <div align="center" style="text-align: left;"><div align="center" class="MsoNormal" style="text-align: left; line-height: 150%;"><div align="center" class="MsoNormal" style="text-align:center;line-height:150%;"><a name="_2cipo4yr3w5d"></a><div align="center" class="MsoNormal" style="line-height: 22.5px;"><div align="center" class="MsoNormal" style="line-height: 150%;"><a name="_gm5sejt4p02f"></a><div align="center" class="MsoNormal" data-custom-class="title" style="text-align: left; line-height: 1.5;"><strong><span style="line-height: 22.5px; font-size: 26px;">TERMS OF USE</span></strong></div><div align="center" class="MsoNormal" style="line-height: 22.5px;"><a name="_7m5b3xg56u7y"></a></div><div align="center" class="MsoNormal" data-custom-class="subtitle" style="text-align: left; line-height: 22.5px;"><br></div><div align="center" class="MsoNormal" data-custom-class="subtitle" style="text-align: left; line-height: 1.5;"><span style="color: rgb(89, 89, 89); font-size: 14.6667px; text-align: justify;"><strong>Last updated <bdt class="block-container question question-in-editor" data-id="e2088df5-25ea-aec9-83d4-6284f5a7e043" data-type="question">__________</bdt></strong></span><span style="color: rgb(166, 166, 166); font-size: 11pt;"><strong>&nbsp;</strong></span></div></div></div><div align="center" class="MsoNormal" style="line-height: 17.25px;"><span style="font-size: 11pt; line-height: 16.8667px;">&nbsp;</span></div><div align="center" class="MsoNormal" style="line-height: 17.25px;"><span style="font-size: 11pt; line-height: 16.8667px;"><br></span></div></div><div class="MsoNormal" style="text-align: justify; line-height: 115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Arial;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="heading_1" style="line-height: 115%;"><a name="_a7mwfgcrtsqn"></a><strong><span style="line-height: 115%; font-family: Arial; font-size: 19px;">AGREEMENT TO TERMS</span></strong></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and <bdt class="block-container question question-in-editor" data-id="4ab94aa9-19d1-61e0-711e-42c7d186232b" data-type="question">__________</bdt><bdt class="block-component"></bdt> ("<bdt class="block-component"></bdt><strong>Company</strong><bdt class="statement-end-if-in-editor"></bdt>", “<strong>we</strong>”, “<strong>us</strong>”, or “<strong>our</strong>”), concerning your access to and use of the <bdt class="block-container question question-in-editor" data-id="92c3b320-1d8b-c74c-db68-d12810736807" data-type="question">__________</bdt> website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the “Site”). You agree that by accessing the Site, you have read, understood, and agreed to be bound by all of these Terms of Use. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms of Use at any time and for any reason. We will alert you about any changes by updating the “Last updated” date of these Terms of Use, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms of Use to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms of Use by your continued use of the Site after the date such revised Terms of Use are posted. &nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><bdt data-type="conditional-block"><bdt class="block-component" data-record-question-key="user_o18_option" data-type="statement"><span style="font-size: 15px;"></span></bdt></bdt></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="heading_1" style="line-height: 115%;"><a name="_4rd71iod99ud"></a><strong><span style="line-height: 115%; font-family: Arial; font-size: 19px;">INTELLECTUAL PROPERTY RIGHTS</span></strong></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">Unless otherwise indicated, the Site is our proprietary
property and all source code, databases, functionality, software, website
designs, audio, video, text, photographs, and graphics on the Site
(collectively, the “Content”) and the trademarks, service marks, and logos
contained therein (the “Marks”) are owned or controlled by us or licensed to
us, and are protected by copyright and trademark laws and various other
intellectual property rights and unfair competition laws of the United States,
foreign jurisdictions, and international conventions. The Content and the Marks are provided on the
Site “AS IS” for your information and personal use only. Except as expressly provided in these Terms
of Use, no part of the Site and no Content or Marks may be copied, reproduced,
aggregated, republished, uploaded, posted, publicly displayed, encoded,
translated, transmitted, distributed, sold, licensed, or otherwise exploited
for any commercial purpose whatsoever, without our express prior written
permission.</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">Provided that you are eligible to use the Site, you are
granted a limited license to access and use the Site and to download or print a
copy of any portion of the Content to which you have properly gained access
solely for your personal, non-commercial use. We reserve all rights not
expressly granted to you in and to the Site, the Content and the Marks.</span></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" data-custom-class="heading_1" style="line-height: 115%;"><a name="_vhkegautf00d"></a><strong><span style="line-height: 115%; font-family: Arial; font-size: 19px;">USER REPRESENTATIONS</span></strong></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><div class="MsoNormal" data-custom-class="body_text" style="line-height: 1.5;"><span style="font-size: 11pt; line-height: 16.8667px; color: rgb(89, 89, 89);">By using the Site, you represent and warrant that: </span> <bdt class="block-container if" data-type="if" id="d2d82ca8-275f-3f86-8149-8a5ef8054af6"><bdt data-type="conditional-block"><bdt class="block-component" data-record-question-key="user_account_option" data-type="statement"></bdt></bdt><span style="color: rgb(89, 89, 89); font-size: 11pt;">(</span><span style="color: rgb(89, 89, 89); font-size: 14.6667px;">1</span><span style="color: rgb(89, 89, 89); font-size: 11pt;">) you have the legal capacity and you agree to comply with these Terms of Use;&nbsp;</span> <bdt class="block-container if" data-type="if" id="8d4c883b-bc2c-f0b4-da3e-6d0ee51aca13"><bdt data-type="conditional-block"><bdt class="block-component" data-record-question-key="user_u13_option" data-type="statement"></bdt></bdt><span style="color: rgb(89, 89, 89); font-size: 11pt;">(</span><span style="color: rgb(89, 89, 89); font-size: 14.6667px;">2</span><span style="color: rgb(89, 89, 89); font-size: 11pt;">) you are not a minor in the jurisdiction in which you reside<bdt class="block-container if" data-type="if" id="76948fab-ec9e-266a-bb91-948929c050c9"><bdt data-type="conditional-block"><bdt class="block-component" data-record-question-key="user_o18_option" data-type="statement"></bdt></bdt>; (</bdt></span><span style="color: rgb(89, 89, 89); font-size: 14.6667px;">3</span><span style="color: rgb(89, 89, 89); font-size: 11pt;">) you will not access the Site through automated or non-human means, whether through a bot, script, or otherwise; (</span><span style="color: rgb(89, 89, 89); font-size: 14.6667px;">4</span><span style="color: rgb(89, 89, 89); font-size: 11pt;">) you will not use the Site for any illegal or unauthorized purpose; and (</span><span style="color: rgb(89, 89, 89); font-size: 14.6667px;">5</span><span style="color: rgb(89, 89, 89); font-size: 11pt;">) your use of the Site will not violate any applicable law or regulation.</span><span style="color: rgb(89, 89, 89); font-size: 14.6667px;"></span></bdt></bdt></div><div class="MsoNormal" data-custom-class="body_text" style="line-height: 1.5;"><span style="font-size: 11pt; line-height: 16.8667px; color: rgb(89, 89, 89);">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="line-height: 1.5;"><span style="font-size: 11pt; line-height: 16.8667px; color: rgb(89, 89, 89);">If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof).&nbsp;</span></div></div><div class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;
line-height:115%;"><span style="font-size:11.0pt;line-height:115%;
Arial;mso-fareast-font-family:Calibri;color:#595959;mso-themecolor:text1;
mso-themetint:166;">&nbsp;</span></div><div class="MsoNormal" style="line-height:115%;"><a name="_esuoutkhaf53"></a> <bdt data-type="conditional-block"><bdt class="block-component" data-record-question-key="user_account_option" data-type="statement"><span style="font-size: 15px;"></span></bdt></bdt></div><div class="MsoNormal" style="line-height:115%;"><a name="_1voziltdxegg"></a><div class="MsoNormal" data-custom-class="heading_1" style="line-height: 17.25px;"><strong><span style="line-height: 24.5333px; font-size: 19px;">PROHIBITED ACTIVITIES</span></strong></div><div class="MsoNormal" style="text-align: justify; line-height: 17.25px;"><span style="font-size: 11pt; line-height: 16.8667px; color: rgb(89, 89, 89);">&nbsp;</span></div><div class="MsoNormal" data-custom-class="body_text" style="text-align: justify; line-height: 1.5;"><span style="font-size: 11pt; line-height: 16.8667px; color: rgb(89, 89, 89);">You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</span><